CREATE TABLE tomcat_ (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(1000) DEFAULT NULL,
  port int DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE webapp_ (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(1000) DEFAULT NULL,
  path varchar(1000) DEFAULT NULL,
  testPage varchar(1000) DEFAULT NULL,
  startup bit(1) DEFAULT NULL,
  tid int DEFAULT NULL,
  deploy bit(1) DEFAULT NULL,
  PRIMARY KEY (id)
);

