/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/@VERSION@
 * Generated at: 2017-04-15 06:37:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class listCategory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/admin/../include/admin/adminHeader.jsp", Long.valueOf(1471253311469L));
    _jspx_dependants.put("/admin/../include/admin/adminFooter.jsp", Long.valueOf(1470905088007L));
    _jspx_dependants.put("/admin/../include/admin/adminNavigator.jsp", Long.valueOf(1482133762257L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<script src=\"js/jquery/2.0.0/jquery.min.js\"></script>\r\n");
      out.write("\t<link href=\"css/bootstrap/3.3.6/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"js/bootstrap/3.3.6/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link href=\"css/back/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("function checkEmpty(id, name){\r\n");
      out.write("\tvar value = $(\"#\"+id).val();\r\n");
      out.write("\tif(value.length==0){\r\n");
      out.write("\t\talert(name+ \"不能为空\");\r\n");
      out.write("\t\t$(\"#\"+id)[0].focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("function checkNumber(id, name){\r\n");
      out.write("\tvar value = $(\"#\"+id).val();\r\n");
      out.write("\tif(value.length==0){\r\n");
      out.write("\t\talert(name+ \"不能为空\");\r\n");
      out.write("\t\t$(\"#\"+id)[0].focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(isNaN(value)){\r\n");
      out.write("\t\talert(name+ \"必须是数字\");\r\n");
      out.write("\t\t$(\"#\"+id)[0].focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("function checkInt(id, name){\r\n");
      out.write("\tvar value = $(\"#\"+id).val();\r\n");
      out.write("\tif(value.length==0){\r\n");
      out.write("\t\talert(name+ \"不能为空\");\r\n");
      out.write("\t\t$(\"#\"+id)[0].focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(parseInt(value)!=value){\r\n");
      out.write("\t\talert(name+ \"必须是整数\");\r\n");
      out.write("\t\t$(\"#\"+id)[0].focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"a\").click(function(){\r\n");
      out.write("\t\tvar deleteLink = $(this).attr(\"deleteLink\");\r\n");
      out.write("\t\tconsole.log(deleteLink);\r\n");
      out.write("\t\tif(\"true\"==deleteLink){\r\n");
      out.write("\t\t\tvar confirmDelete = confirm(\"确认要删除\");\r\n");
      out.write("\t\t\tif(confirmDelete)\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("})\r\n");
      out.write("</script>\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"navitagorDiv\">\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top navbar-inverse\">\r\n");
      out.write("\t\t<img style=\"margin-left:10px;margin-right:0px\" class=\"pull-left\" src=\"img/site/tmallbuy.png\" height=\"45px\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"#nowhere\">天猫后台</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"admin_category_list\">分类管理</a>\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"admin_user_list\">用户管理</a>\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"admin_order_list\">订单管理</a>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#addForm\").submit(function(){\r\n");
      out.write("\t\tif(checkEmpty(\"name\",\"分类名称\"))\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>分类管理</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"workingArea\">\r\n");
      out.write("\t<h1 class=\"label label-info\" >分类管理</h1>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"listDataTableDiv\">\r\n");
      out.write("\t\t<table class=\"table table-striped table-bordered table-hover  table-condensed\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr class=\"success\">\r\n");
      out.write("\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t<th>图片</th>\r\n");
      out.write("\t\t\t\t\t<th>分类名称</th>\r\n");
      out.write("\t\t\t\t\t<th>属性管理</th>\r\n");
      out.write("\t\t\t\t\t<th>产品管理</th>\r\n");
      out.write("\t\t\t\t\t<th>编辑</th>\r\n");
      out.write("\t\t\t\t\t<th>删除</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"pageDiv\">\r\n");
      out.write("\t\t");
//@include file="../include/admin/adminPage.jsp" 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"panel panel-warning addDiv\">\r\n");
      out.write("\t  <div class=\"panel-heading\">新增分类</div>\r\n");
      out.write("\t  <div class=\"panel-body\">\r\n");
      out.write("\t    \t<form method=\"post\" id=\"addForm\" action=\"admin_category_add\" enctype=\"multipart/form-data1\">\r\n");
      out.write("\t    \t\t<table class=\"addTable\">\r\n");
      out.write("\t    \t\t\t<tr>\r\n");
      out.write("\t    \t\t\t\t<td>分类名称</td>\r\n");
      out.write("\t    \t\t\t\t<td><input  id=\"name\" name=\"name\" type=\"text\" class=\"form-control\"></td>\r\n");
      out.write("\t    \t\t\t</tr>\r\n");
      out.write("\t    \t\t\t<tr>\r\n");
      out.write("\t    \t\t\t\t<td>分类圖片</td>\r\n");
      out.write("\t    \t\t\t\t<td>\r\n");
      out.write("\t    \t\t\t\t\t<input id=\"categoryPic\" type=\"file\" name=\"filepath\" />\r\n");
      out.write("\t    \t\t\t\t</td>\r\n");
      out.write("\t    \t\t\t</tr>\r\n");
      out.write("\t    \t\t\t<tr class=\"submitTR\">\r\n");
      out.write("\t    \t\t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t    \t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\">提 交</button>\r\n");
      out.write("\t    \t\t\t\t</td>\r\n");
      out.write("\t    \t\t\t</tr>\r\n");
      out.write("\t    \t\t</table>\r\n");
      out.write("\t    \t</form>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /admin/listCategory.jsp(42,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${thecs}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /admin/listCategory.jsp(42,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("c");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t<td><img height=\"40px\" src=\"img/category/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(".jpg\"></td>\r\n");
            out.write("\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t \t\r\n");
            out.write("\t\t\t\t\t<td><a href=\"admin_property_list?cid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"><span class=\"glyphicon glyphicon-th-list\"></span></a></td>\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t<td><a href=\"admin_product_list?cid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"><span class=\"glyphicon glyphicon-shopping-cart\"></span></a></td>\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t<td><a href=\"admin_category_edit?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"><span class=\"glyphicon glyphicon-edit\"></span></a></td>\r\n");
            out.write("\t\t\t\t\t<td><a deleteLink=\"true\" href=\"admin_category_delete?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"><span class=\" \tglyphicon glyphicon-trash\"></span></a></td>\r\n");
            out.write("\t\r\n");
            out.write("\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
